#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/08c22f86-45ce-43f1-9e18-3b07d56799ef/ # 
title: Book API
version: v2.0
# baseUri: http://localhost:8081/api

types:
  BookItem:
    properties:
      name:
        type: string
  MessageResponse: 
    properties: 
      message: string
      code: integer  
/books:
  post:
      displayName: Create new book
      description: Create a new book.
      body:
        application/json:
          type: BookItem
      responses:
        201:
          body:
            application/json:
              type: MessageResponse
  /{bookId}:
    get:
      displayName: Retrieve a book
      description: Retrieve a book
      queryParameters:
      responses:
        200:
          body:
            application/json:
              type: BookItem
    